#Configuration for EKF localization node

frequency: 10
sensor_timeout: 0.1
two_d_mode: true
publish_tf: true
publish_acceleration: true
transform_time_offset: 0.0
transform_timeout: 0.0

# Coordinate frame specification
odom_frame: odom
base_link_frame: base_link
world_frame: odom
#map_frame: map
print_diagnostics: true

# The odom0 configuration
#odom0: /odometry/filtered
#odom0_config: [true, true, false,
#             false, false, true,
#             false, false, false,
#             true, true, true]
#odom0_differential: true
#odom0_relative: true
#odom0_queue_size: 10
#odom0_nodelay: false

# The imu0 configuration
imu0: /imu_data
imu0_config: [false,  false,  false,
                true, true, true,
                false,  false, false,
                false, false, false,
                true, true, true]
imu0_differential: false
imu0_relative: false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true
imu0_nodelay: false
imu0_pose_rejection_threshold: 0.8
imu0_twist_rejection_threshold: 0.8

process_noise_covariance: [0.05,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0, 0.05,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0, 0.06,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0, 0.03,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0, 0.03,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0, 0.06,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,0.025,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0, 0.025,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,  0.04,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0, 0.01,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0, 0.01,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0, 0.02,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0, 0.01,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0, 0.01,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0, 0.015]


initial_estimate_covariance: [1e-9,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0, 1e-9,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0, 1e-9,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0, 1e-9,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0, 1e-9,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0, 1e-9,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0, 1e-9,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0, 1e-9,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0, 1e-9,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0, 1e-9,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  1e-9,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,  1e-9,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,  1e-9,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0, 1e-9,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0, 1e-9]
